FROM alpine:3.7

# Install CA certificates
RUN apk add --no-cache --virtual=build-dependencies ca-certificates git

ADD bmrg-oauth2-proxy /bin/
#RUN 'sh' '-c' 'go get github.com/bitly/oauth2_proxy'

# Expose the ports we need and setup the ENTRYPOINT w/ the default argument
# to be pass in.
EXPOSE 8080 4180
ENTRYPOINT [ "./bin/bmrg-oauth2-proxy" ]